[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-set-metadata",
  "allow-set-playback-state",
  "allow-set-position-state",
  "allow-register-listener",
  "allow-remove-listener",
  "allow-check-permissions",
  "allow-request-permissions",
]
