[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-exit-app",
  "allow-set-status-bar",
  "allow-hide-status-bar",
  "allow-get-system-font-scale",
  "allow-get-screen-orientation",
  "allow-set-screen-orientation",
  "allow-register-listener",
  "allow-remove-listener",
  "allow-check-permissions",
  "allow-request-permissions",
]
