[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-exit-app",
  "allow-set-status-bar",
  "allow-hide-status-bar",
  "allow-get-system-font-scale",
  "allow-set-screen-orientation",
]
